[colors.bright]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x1d2021"
foreground = "0xd4be98"

[font.normal]
family = "mononoki Nerd Font Mono"

[font]
size = 9.0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Super"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.94

[window.class]
general = "Alacritty"
